config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  resources :news
  delete '/news/:id' => 'news#destroy', as: 'destroy_news'

  root 'main_pages#home'

  get 'main_pages/home'

  get 'main_pages/about'

  devise_for :users

  post 'contacts/:id/delete_avatar' => 'contacts#delete_avatar', as: 'delete_avatar'
  
  post 'news/:id/up' => 'news#up', as: 'news_up'
  post 'news/:id/down' => 'news#down', as: 'news_down'

  post 'contacts/:id/up' => 'contacts#up', as: 'contact_up'
  post 'contacts/:id/down' => 'contacts#down', as: 'contact_down'

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :is_user_login
  before_action :is_user_admin, except: [:show, :index]

  def new
    @one_news = News.new
  end

  def create
    @one_news = News.new(news_params)
    if @one_news.save
        redirect_to '/news', notice: "Новость создана"
    else
        redirect_to '/news', alert: "Ошибка при создании новости"
    end
  end


  def show
  end


  def index
    @all_news = News.all.order(row_num: :desc)
  end

  def edit
    @one_news = News.find_by(id: params[:id])
  end

  def update
    @one_news = News.find_by(id: params[:id])
    if @one_news.update(news_params)
        @all_news = News.all.order(row_num: :desc)
        render :index, notice: 'Новость изменена'
    else
        render action: 'edit'
    end
  end


  def destroy
    @selected_news = News.find_by(id: params[:id])
    
    unless @selected_news.nil?
      @selected_news.destroy
      redirect_to '/news', notice: "Новость #{@selected_news.title_en}/#{@selected_news.title_ru} удалена"
    else 
      redirect_to '/news', alert: "Новость с id=#{params[:id]} отсутствует"
    end

  end



  #поднять новость в списке
  def up
    one_news = News.find_by(id: params[:id])
    all_news = News.all

    if up_object(one_news, all_news)
      redirect_to '/news', notice: "Новость #{one_news.title_en} поднята в списке"
    else
      redirect_to '/news', notice: "Новость #{one_news.title_en} первая в списке"    
    end       

  end

  #опустить новость в списке
  def down
    one_news = News.find_by(id: params[:id])
    all_news = News.all

    if down_object(one_news, all_news)
      redirect_to '/news', notice: "Новость #{one_news.title_en} опущена в списке"
    else
      redirect_to '/news', notice: "Новость #{one_news.title_en} последняя в списке"    
    end
  end



private

    def is_user_login
      if current_user.nil?
        redirect_to '/users/sign_in', alert: "Перед работой с сервисом необходимо залогиниться"
      end
    end

    def is_user_admin 
      unless current_user.admin?
        redirect_to '/news', alert: "Только админ может создавать новости"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:row_num, :title_en, :text_en, :title_ru, :text_ru)
    end

end

app/helpers/news_helper.rb
module NewsHelper
	
	def next_row_num_news(news)
		if news.id.nil?
			if News.all.count == 0
				return 1
			else
				News.all.order(row_num: :desc).first.row_num+1
			end
		else 
			news.row_num
		end
	end

end

app/views/news/create.html.erb
<h1>News#create</h1>
<p>Find me in app/views/news/create.html.erb</p>

app/views/news/edit.html.erb
<h1>Изменить новость</h1>

<%= form_for @one_news do |n| %>
	id: <%= @one_news.id %><br><br>

	Номер по порядку:
	<%= n.text_field :row_num %><br/><br/>

	Английский заголовок:
	<%= n.text_field :title_en %><br/>

	Английский текст:
	<%= n.text_area :text_en %><br/><br/><br/>


	Русский заголовок:
	<%= n.text_field :title_ru %><br/>

	Русский текст:
	<%= n.text_area :text_ru %><br/><br/>


	<%= n.submit "Обновить" %><br>
	<%=link_to "Назад", news_index_path %>


<% end %>

app/views/news/index.html.erb
<h1>All news</h1>

<% if current_user.admin? %>
	<%= link_to "Create news", new_news_path %> <br><br>
<% end %>

<% @all_news.each do |n| %>
	
	ID=<%= n.id %><br>
	row_num=<%= n.row_num %><br>
	
	<% if current_user_lang == "ru" || current_user_admin? %>
		title_ru=<%= n.title_ru %><br>
		text_ru=<%= n.text_ru %><br><br>
	<% end %>

	<% if current_user_lang != "ru" || current_user_admin? %>	
		title_en=<%= n.title_en %><br>
		text_en=<%= n.text_en %><br><br>
	<% end %>
	
	Posted <%= time_ago_in_words(n.created_at) %> <br/>	
	  

<% if current_user.admin? %>
	<%= link_to "Edit", edit_news_path(n.id) %> | 
	<%= link_to "Delete", destroy_news_path(n.id), :data => {:confirm => "Delete #{n.title_ru}/#{n.title_en}?"}, method: :delete %> 
	<br>
	<%= link_to "Up", news_up_path(n.id), method: :post  %> | 
	<%= link_to "Down", news_down_path(n), method: :post %>

<% end %>


	<br><br><br>

	

<% end %>

app/views/news/new.html.erb
<h1>Новая новость</h1>

<%= form_for @one_news do |n| %>
	
	Номер по порядку:
	<%= n.text_field :row_num, :value => next_row_num(@one_news, News.all) %><br/><br/>

	Английский заголовок:
	<%= n.text_field :title_en %><br/>

	Английский текст:
	<%= n.text_area :text_en %><br/><br/><br/>


	Русский заголовок:
	<%= n.text_field :title_ru %><br/>

	Русский текст:
	<%= n.text_area :text_ru %><br/><br/>


	<%= n.submit "Создать" %><br>
	<%=link_to "Назад", news_index_path %>

<% end %>

app/views/news/show.html.erb
<h1>News#show</h1>
<p>Find me in app/views/news/show.html.erb</p>