config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  resources :news
  delete '/news/:id' => 'news#destroy', as: 'destroy_news'

  root 'main_pages#home'

  get 'main_pages/home'

  get 'main_pages/about'

  devise_for :users

  post 'contacts/:id/delete_avatar' => 'contacts#delete_avatar', as: 'delete_avatar'
  
  post 'news/:id/up' => 'news#up', as: 'news_up'
  post 'news/:id/down' => 'news#down', as: 'news_down'

  post 'contacts/:id/up' => 'contacts#up', as: 'contact_up'
  post 'contacts/:id/down' => 'contacts#down', as: 'contact_down'

end

app/models/contact.rb
class Contact < ActiveRecord::Base

    #attr_accessible :avatar
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    validates_attachment :avatar, size: { less_than: 1.megabytes }


  	def exists_avatar?
  		if self.avatar.nil?
  			false
  		else
  			true
  		end
  	end

    def avatar_url
      if self.avatar.file?
        avatar.url
      else
        ""
      end
      #Rails.application.config.current_host + avatar.url
      #avatar.url
    end


  	def avatar_medium_url
        avatar.url(:medium)
    end
    
  	def avatar_thumb_url
        avatar.url(:thumb)
    end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :is_user_login, except: [:show, :index]
  before_action :is_user_admin, except: [:show, :index]

  before_action :set_contact, only: [:show, :edit, :update, :destroy, :delete_avatar]


  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.order(row_num: :desc)
    respond_to do |format|
      format.html { is_user_login }
      format.json {}
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    respond_to do |format|
      format.html { is_user_login }
      format.json {}
    end
  end


  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_avatar
    @contact.avatar = nil
    if @contact.save
        redirect_to "/contacts/#{@contact.id}/edit", notice: "Изображение удалено"
    else
        redirect_to "/contacts/#{@contact.id}/edit", alert: "Изображение не удалено"    
    end
  end

  def up
    one_contact = Contact.find_by(id: params[:id])    
    all_contacts = Contact.all

    if up_object(one_contact, all_contacts)
      redirect_to '/contacts', notice: "Контакт #{one_contact.name_en} поднят в списке"
    else
      redirect_to '/contacts', notice: "Контакт #{one_contact.name_en} уже первый в списке"    
    end
  end


  def down
    one_contact = Contact.find_by(id: params[:id])    
    all_contacts = Contact.all

    if down_object(one_contact, all_contacts)
      redirect_to '/contacts', notice: "Контакт #{one_contact.name_en} опущен в списке"
    else
      redirect_to '/contacts', notice: "Контакт #{one_contact.name_en} уже последний в списке"    
    end
  end



  private

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:row_num, :name_en, :name_ru, :description_en, :description_ru, :phone, :email, :avatar)
    end


    def is_user_login
      if current_user.nil?
        redirect_to '/users/sign_in', alert: "Перед работой с сервисом необходимо залогиниться"
      end
    end

    def is_user_admin 
      unless current_user.admin?
        redirect_to '/contacts', alert: "Только админ может редактировать данные"
      end
    end

end

app/helpers/contacts_helper.rb
module ContactsHelper

	def next_row_num_contacts(contact)
		if contact.id.nil?
			if Contact.all.count == 0
				return 1
			else
				Contact.all.order(row_num: :desc).first.row_num+1
			end
		else 
			contact.row_num
		end
	end

	

end

app/views/contacts/_form.html.erb
<%= form_for @contact, :html => { :multipart => true } do |f| %>

  
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :row_num %><br>
    <%= f.number_field :row_num, :value => next_row_num_contacts(@contact) %>
  </div>
  <div class="field">
    <%= f.label :name_en %><br>
    <%= f.text_field :name_en %>
  </div>
  <div class="field">
    <%= f.label :name_ru %><br>
    <%= f.text_field :name_ru %>
  </div>
  <div class="field">
    <%= f.label :description_en %><br>
    <%= f.text_field :description_en %>
  </div>
  <div class="field">
    <%= f.label :description_ru %><br>
    <%= f.text_field :description_ru %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">

        <% if @contact.avatar.exists? %>
            Avatar: <%= image_tag @contact.avatar.url(:thumb) %>
            <%= link_to 'Delete avatar', delete_avatar_path(@contact), method: :post %>
        <% end %>    <br>

    <%= f.file_field :avatar %>
  </div>

  
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<% if current_user_admin? %>
  <%= link_to 'New Contact', new_contact_path %>
<% end %>

<h1>Список контактов</h1>

    <% @contacts.each do |contact| %>
        
        Row num: <%= contact.row_num %><br>

        <% if current_user_lang == "ru" || current_user_admin? %>
            Name ru: <%= contact.name_ru %><br>
            Description ru: <%= contact.description_ru %><br>
        <% end %>

        <% if current_user_lang != "ru" || current_user_admin? %>
            Name en: <%= contact.name_en %><br>
            Description en: <%= contact.description_en %><br>
        <% end %>

        Phone: <%= contact.phone %><br>
        Email: <%= contact.email %><br>

        <% if contact.avatar.exists? %>
            Avatar: <%= image_tag contact.avatar.url(:thumb) %>
        <% end %>

        <% if current_user_admin? %>
        <br>
        <%= link_to 'Show', contact %> |
        <%= link_to 'Edit', edit_contact_path(contact) %> |
        <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %><br>
        <%= link_to 'Up', contact_up_path(contact), method: :post %> |
        <%= link_to 'Down', contact_down_path(contact), method: :post %>

        <% end %>

        <br><br>
        <br><br>
    
    <% end %>

<br>

app/views/contacts/new.html.erb
<h1>New Contact</h1>


<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<h2>Контактные данные</h2>

<p>
  <strong>Row num:</strong>
  <%= @contact.row_num %>
</p>

<p>
  <strong>Name en:</strong>
  <%= @contact.name_en %>
</p>

<p>
  <strong>Name ru:</strong>
  <%= @contact.name_ru %>
</p>

<p>
  <strong>Description en:</strong>
  <%= @contact.description_en %>
</p>

<p>
  <strong>Description ru:</strong>
  <%= @contact.description_ru %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

        <% if @contact.avatar.exists? %>
            Avatar: <%= image_tag @contact.avatar.url(:thumb) %> <br/>

            url: <%= @contact.avatar.url %>
        <% end %>

        <br>

<% if current_user_admin? %>
<%= link_to 'Edit', edit_contact_path(@contact) %> |
<% end %>

<%= link_to 'Back', contacts_path %>